## **Loading Data to MySQL**

from sqlalchemy import create_engine

username = 'your_username' #root
password = 'your_password'
host = 'localhost'  #for python connection always localhost
port = '3306'
database = 'your_database'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')
table_name = 'your_table'

df.to_sql(name=table_name, con=engine, if_exists='replace', index=False) #instead of replace we can choose append also

query = f'SELECT * FROM {table_name} LIMIT 5;'
pd.read_sql(query, engine)

In [3]:
import pandas as pd

df = pd.read_csv('../data/final/consumer_final_data.csv')
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,discount_applied,previous_purchases,payment_method,frequency_of_purchases,purchase_outlier_flag,age_group,high_value_transaction_flag,promotion_exposure_flag,express_shipping_flag,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,True,14,Venmo,Fortnightly,False,Adult,0,1,1,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,True,2,Cash,Fortnightly,False,Teen,1,1,1,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,True,23,Credit Card,Weekly,False,Adult,1,1,0,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,True,49,Paypal,Weekly,False,Teen,1,1,1,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,True,31,Paypal,Annually,False,Adult,0,1,0,365

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus #added this because of special characters in password

username = 'root'
password =  quote_plus('your_password') # Used quote_plus to encode special characters
host = 'localhost'
port = '3306'
database = 'consumer_behaviour'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')
table_name = 'consumer_data'

df.to_sql(name=table_name, con=engine, if_exists='replace', index=False) #instead of replace we can choose append also

query = f'SELECT * FROM {table_name} LIMIT 5;'
pd.read_sql(query, engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,discount_applied,previous_purchases,payment_method,frequency_of_purchases,purchase_outlier_flag,age_group,high_value_transaction_flag,promotion_exposure_flag,express_shipping_flag,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,1,14,Venmo,Fortnightly,0,Adult,0,1,1,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,1,2,Cash,Fortnightly,0,Teen,1,1,1,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,1,23,Credit Card,Weekly,0,Adult,1,1,0,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,1,49,Paypal,Weekly,0,Teen,1,1,1,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,1,31,Paypal,Annually,0,Adult,0,1,0,365

Data Pushed to SQL DB